<#
.SYNOPSIS
    ZerodhaKiteGit — interactive env + Docker (Windows, mirrors setup.sh).

.PARAMETER Env
    local = backend\.env + docker compose.yml
    prod  = backend\.env.production + docker-compose.prod.yml

.EXAMPLE
    .\setup.ps1 -Env local
    .\setup.ps1 -Env prod
#>
param(
    [Parameter(Mandatory = $false)]
    [ValidateSet("local", "prod")]
    [string]$Env = ""
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $Root

function Write-Header($msg) {
    Write-Host ""
    Write-Host "=== $msg ===" -ForegroundColor Cyan
}

function New-SecretKey {
    $s = $null
    try { $s = python -c "import secrets; print(secrets.token_hex(32))" 2>$null } catch { }
    if (-not $s) {
        $bytes = New-Object byte[] 32
        [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
        $s = [BitConverter]::ToString($bytes).Replace("-", "").ToLower()
    }
    return $s
}

if (-not $Env) {
    Write-Host "ZerodhaKiteGit setup" -ForegroundColor Green
    Write-Host "  local - backend\.env + http://localhost:5175"
    Write-Host "  prod  - backend\.env.production + compose prod"
    $Env = Read-Host "Enter environment (local/prod)"
}

# ─── LOCAL ────────────────────────────────────────────────────────────────────
if ($Env -eq "local") {
    Write-Header "Local stack"
    if (-not (Test-Path "backend\.env")) {
        Write-Host "Creating backend\.env (prompts)..." -ForegroundColor Yellow
        $sk = New-SecretKey
        $gid = Read-Host "GOOGLE_CLIENT_ID"
        $gsec = Read-Host "GOOGLE_CLIENT_SECRET" -AsSecureString
        $gsecPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
            [Runtime.InteropServices.Marshal]::SecureStringToBSTR($gsec))
        $groq = Read-Host "GROQ_API_KEY (optional)"
        $rpId = Read-Host "RAZORPAY_KEY_ID (optional)"
        $rpSec = Read-Host "RAZORPAY_KEY_SECRET (optional)"
        $smtp = Read-Host "SMTP Gmail (optional)"
        $smtpPass = Read-Host "SMTP app password (optional)"

        @"
# Generated by setup.ps1 local
SERVER_HOST=0.0.0.0
SERVER_PORT=8003
DEBUG=False
BACKEND_URL=http://localhost:8003
FRONTEND_URL=http://localhost:5175
CORS_ORIGINS=http://localhost:3000,http://localhost:3001,http://localhost:5175,http://localhost:8003
SECRET_KEY=$sk
DATABASE_PATH=database.db
GOOGLE_CLIENT_ID=$gid
GOOGLE_CLIENT_SECRET=$gsecPlain
GOOGLE_REDIRECT_URI=http://localhost:8003/api/auth/google/callback
GROQ_API_KEY=$groq
GROQ_MODEL=llama-3.1-8b-instant
LOG_LEVEL=INFO
SMTP_SERVER=smtp.gmail.com
USERNAME_EMAIL=$smtp
PASSWORD_EMAIL=$smtpPass
EMAIL_FROM=$smtp
RAZORPAY_KEY_ID=$rpId
RAZORPAY_KEY_SECRET=$rpSec
RAZORPAY_WEBHOOK_SECRET=
"@ | Set-Content -Path "backend\.env" -Encoding utf8
        Write-Host "backend\.env created." -ForegroundColor Green
    }
    docker compose up --build -d
    Write-Host "http://localhost:5175" -ForegroundColor Green
}

# ─── PROD ─────────────────────────────────────────────────────────────────────
elseif ($Env -eq "prod") {
    Write-Header "Production stack"
    if (-not (Test-Path "backend\.env.production")) {
        Write-Host "Creating backend\.env.production (prompts)..." -ForegroundColor Yellow
        $base = Read-Host "Public site URL [https://drpinfotech.com]"
        if (-not $base) { $base = "https://drpinfotech.com" }
        $base = $base.TrimEnd("/")
        $sk = New-SecretKey
        Write-Host "Google OAuth (production client)" -ForegroundColor Yellow
        $gid = Read-Host "GOOGLE_CLIENT_ID"
        $gsec = Read-Host "GOOGLE_CLIENT_SECRET" -AsSecureString
        $gsecPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
            [Runtime.InteropServices.Marshal]::SecureStringToBSTR($gsec))
        $groq = Read-Host "GROQ_API_KEY (optional)"
        $rpId = Read-Host "RAZORPAY_KEY_ID"
        $rpSec = Read-Host "RAZORPAY_KEY_SECRET" -AsSecureString
        $rpSecPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
            [Runtime.InteropServices.Marshal]::SecureStringToBSTR($rpSec))
        $rwh = Read-Host "RAZORPAY_WEBHOOK_SECRET (optional)"
        $smtp = Read-Host "SMTP Gmail"
        $smtpPass = Read-Host "SMTP app password" -AsSecureString
        $smtpPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
            [Runtime.InteropServices.Marshal]::SecureStringToBSTR($smtpPass))
        $redirect = "$base/api/auth/google/callback"

        @"
# Generated by setup.ps1 prod
SERVER_HOST=0.0.0.0
SERVER_PORT=8003
DEBUG=False
BACKEND_URL=$base
FRONTEND_URL=$base
CORS_ORIGINS=$base
SECRET_KEY=$sk
DATABASE_PATH=database.db
GOOGLE_CLIENT_ID=$gid
GOOGLE_CLIENT_SECRET=$gsecPlain
GOOGLE_REDIRECT_URI=$redirect
GROQ_API_KEY=$groq
GROQ_MODEL=llama-3.1-8b-instant
LOG_LEVEL=INFO
SMTP_SERVER=smtp.gmail.com
USERNAME_EMAIL=$smtp
PASSWORD_EMAIL=$smtpPlain
EMAIL_FROM=$smtp
RAZORPAY_KEY_ID=$rpId
RAZORPAY_KEY_SECRET=$rpSecPlain
RAZORPAY_WEBHOOK_SECRET=$rwh
"@ | Set-Content -Path "backend\.env.production" -Encoding utf8
        Write-Host "backend\.env.production created." -ForegroundColor Green
        Write-Host "Google Console: origin $base  redirect $redirect"
    }
    docker compose -f docker-compose.prod.yml up --build -d
    Write-Host "Prod stack up. Logs: docker compose -f docker-compose.prod.yml logs -f" -ForegroundColor Green
}
else {
    Write-Host "Use -Env local or -Env prod" -ForegroundColor Red
    exit 1
}
