#!/usr/bin/env bash
# ZerodhaKiteGit — interactive env + Docker (same idea as toolsDRP setup.sh)
#
# Usage:
#   bash setup.sh local   # Creates backend/.env if missing, then docker compose up --build
#   bash setup.sh prod    # Creates backend/.env.production if missing, then docker-compose.prod.yml up --build
#
set -euo pipefail

ENV="${1:-}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

header() { echo ""; echo "=== $1 ==="; }

if [[ -z "$ENV" ]]; then
  echo "ZerodhaKiteGit setup"
  echo "Usage: bash setup.sh [local|prod]"
  read -rp "Enter environment (local/prod): " ENV
fi

gen_secret() {
  python3 -c "import secrets; print(secrets.token_hex(32))" 2>/dev/null || openssl rand -hex 32
}

# ─── Interactive production env (backend/.env.production) ─────────────────────
generate_env_production() {
  header "Generating backend/.env.production"

  if [[ -f "backend/.env.production" ]]; then
    echo "backend/.env.production already exists — skipping."
    echo "Remove it and re-run to regenerate."
    return 0
  fi

  read -rp "Public site URL [https://drpinfotech.com]: " BASE_URL
  BASE_URL="${BASE_URL:-https://drpinfotech.com}"
  BASE_URL="${BASE_URL%/}"

  SECRET_KEY="$(gen_secret)"

  echo "Google OAuth (production client — must match Google Cloud Console for this URL)"
  read -rp "GOOGLE_CLIENT_ID: " GOOGLE_CLIENT_ID
  read -rsp "GOOGLE_CLIENT_SECRET: " GOOGLE_CLIENT_SECRET
  echo ""

  read -rp "GROQ_API_KEY (optional, Enter to skip): " GROQ_API_KEY
  read -rp "RAZORPAY_KEY_ID: " RAZORPAY_KEY_ID
  read -rsp "RAZORPAY_KEY_SECRET: " RAZORPAY_KEY_SECRET
  echo ""
  read -rp "RAZORPAY_WEBHOOK_SECRET (optional): " RAZORPAY_WEBHOOK_SECRET

  read -rp "SMTP / Gmail address: " USERNAME_EMAIL
  read -rsp "SMTP app password: " PASSWORD_EMAIL
  echo ""

  REDIRECT="${BASE_URL}/api/auth/google/callback"

  cat > backend/.env.production <<EOF
# Generated by setup.sh prod — do not commit
SERVER_HOST=0.0.0.0
SERVER_PORT=8003
DEBUG=False

BACKEND_URL=${BASE_URL}
FRONTEND_URL=${BASE_URL}
CORS_ORIGINS=${BASE_URL}

SECRET_KEY=${SECRET_KEY}
DATABASE_PATH=database.db

GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
GOOGLE_REDIRECT_URI=${REDIRECT}

GROQ_API_KEY=${GROQ_API_KEY}
GROQ_MODEL=llama-3.1-8b-instant
LOG_LEVEL=INFO

SMTP_SERVER=smtp.gmail.com
USERNAME_EMAIL=${USERNAME_EMAIL}
PASSWORD_EMAIL=${PASSWORD_EMAIL}
EMAIL_FROM=${USERNAME_EMAIL}

RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
RAZORPAY_WEBHOOK_SECRET=${RAZORPAY_WEBHOOK_SECRET}
EOF

  echo "backend/.env.production created."
  echo "Register in Google Console: JS origin ${BASE_URL}  redirect ${REDIRECT}"
}

# ─── Interactive local env (backend/.env) ─────────────────────────────────────
generate_env_local() {
  header "Generating backend/.env (local Docker)"

  if [[ -f "backend/.env" ]]; then
    echo "backend/.env already exists — skipping."
    return 0
  fi

  SECRET_KEY="$(gen_secret)"

  echo "Google OAuth (use a dev client with localhost redirect in Console)"
  read -rp "GOOGLE_CLIENT_ID: " GOOGLE_CLIENT_ID
  read -rsp "GOOGLE_CLIENT_SECRET: " GOOGLE_CLIENT_SECRET
  echo ""

  read -rp "GROQ_API_KEY (optional): " GROQ_API_KEY
  read -rp "RAZORPAY_KEY_ID (optional): " RAZORPAY_KEY_ID
  read -rsp "RAZORPAY_KEY_SECRET (optional): " RAZORPAY_KEY_SECRET
  echo ""

  read -rp "SMTP Gmail (optional): " USERNAME_EMAIL
  read -rsp "SMTP app password (optional): " PASSWORD_EMAIL
  echo ""

  cat > backend/.env <<EOF
# Generated by setup.sh local — do not commit
SERVER_HOST=0.0.0.0
SERVER_PORT=8003
DEBUG=False

BACKEND_URL=http://localhost:8003
FRONTEND_URL=http://localhost:5175
CORS_ORIGINS=http://localhost:3000,http://localhost:3001,http://localhost:5175,http://localhost:8003

SECRET_KEY=${SECRET_KEY}
DATABASE_PATH=database.db

GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
GOOGLE_REDIRECT_URI=http://localhost:8003/api/auth/google/callback

GROQ_API_KEY=${GROQ_API_KEY}
GROQ_MODEL=llama-3.1-8b-instant
LOG_LEVEL=INFO

SMTP_SERVER=smtp.gmail.com
USERNAME_EMAIL=${USERNAME_EMAIL}
PASSWORD_EMAIL=${PASSWORD_EMAIL}
EMAIL_FROM=${USERNAME_EMAIL}

RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
RAZORPAY_WEBHOOK_SECRET=
EOF

  echo "backend/.env created."
}

# ─── LOCAL ────────────────────────────────────────────────────────────────────
if [[ "$ENV" == "local" ]]; then
  header "Local stack (docker-compose.yml)"
  [[ ! -f "backend/.env" ]] && generate_env_local
  docker compose up --build -d
  echo ""
  echo "Open http://localhost:5175"

# ─── PROD ───────────────────────────────────────────────────────────────────────
elif [[ "$ENV" == "prod" ]]; then
  header "Production stack (docker-compose.prod.yml)"
  [[ ! -f "backend/.env.production" ]] && generate_env_production
  docker compose -f docker-compose.prod.yml up --build -d
  echo ""
  echo "Stack up. Frontend: http://127.0.0.1:5175 (put nginx/SSL in front)"
  echo "Logs: docker compose -f docker-compose.prod.yml logs -f"

else
  echo "Unknown environment: $ENV. Use 'local' or 'prod'."
  exit 1
fi
